/// @description Actor controller constants and default tuning macros.

#macro ACTOR_CONTROLLER_VERSION "0.2.0"

#macro ACTOR_DEBUG_DEFAULT false
#macro ACTOR_DEBUG_DRAW_COLLISION_DEFAULT false
#macro ACTOR_DEBUG_DRAW_PROBES_DEFAULT false
#macro ACTOR_DEBUG_DRAW_VECTORS_DEFAULT false
#macro ACTOR_DEBUG_PRINT_EVENTS_DEFAULT false
#macro ACTOR_DEBUG_TEXT_X_DEFAULT 16
#macro ACTOR_DEBUG_TEXT_Y_DEFAULT 16

#macro ACTOR_STEP_FPS 60
#macro ACTOR_EPSILON 0.0001
#macro ACTOR_MAX_COLLISION_ITERATIONS 16
#macro ACTOR_MAX_MOVE_STEP_PIXELS 2
#macro ACTOR_HARD_SPEED_CAP 24

#macro ACTOR_JUMP_BUFFER_FRAMES_DEFAULT 8
#macro ACTOR_GROUND_COYOTE_FRAMES_DEFAULT 8
#macro ACTOR_WALL_COYOTE_FRAMES_DEFAULT 6
#macro ACTOR_LEDGE_COYOTE_FRAMES_DEFAULT 5
#macro ACTOR_DROP_THROUGH_FRAMES_DEFAULT 12
#macro ACTOR_WALL_JUMP_LOCKOUT_FRAMES_DEFAULT 6

#macro ACTOR_SPRAY_GROUND_LIFT_SUPPRESS true
#macro ACTOR_GROUND_LAUNCH_CHARGE_MIN_DEFAULT 0.65
#macro ACTOR_WATER_MAX_DEFAULT 100
#macro ACTOR_EMPTY_SPRAY_GRACE_FRAMES_DEFAULT 3

#macro ACTOR_ABILITY_NONE 0
#macro ACTOR_ABILITY_JUMP (1 << 0)
#macro ACTOR_ABILITY_WALL_SLIDE (1 << 1)
#macro ACTOR_ABILITY_WALL_JUMP (1 << 2)
#macro ACTOR_ABILITY_LEDGE_GRAB (1 << 3)
#macro ACTOR_ABILITY_SLIDE (1 << 4)
#macro ACTOR_ABILITY_SPRAY (1 << 5)
#macro ACTOR_ABILITY_CHARGE_SPRAY (1 << 6)
#macro ACTOR_ABILITY_DROP_THROUGH (1 << 7)
#macro ACTOR_ABILITY_ALL (ACTOR_ABILITY_JUMP | ACTOR_ABILITY_WALL_SLIDE | ACTOR_ABILITY_WALL_JUMP | ACTOR_ABILITY_LEDGE_GRAB | ACTOR_ABILITY_SLIDE | ACTOR_ABILITY_SPRAY | ACTOR_ABILITY_CHARGE_SPRAY | ACTOR_ABILITY_DROP_THROUGH)
