/// @description Actor controller constants and default tuning macros.

#macro ACTOR_CONTROLLER_VERSION "0.7.0"

#macro ACTOR_DEBUG_DEFAULT false
#macro ACTOR_DEBUG_DRAW_COLLISION_DEFAULT false
#macro ACTOR_DEBUG_DRAW_PROBES_DEFAULT false
#macro ACTOR_DEBUG_DRAW_VECTORS_DEFAULT false
#macro ACTOR_DEBUG_PRINT_EVENTS_DEFAULT false
#macro ACTOR_DEBUG_TEXT_X_DEFAULT 16
#macro ACTOR_DEBUG_TEXT_Y_DEFAULT 16
#macro ACTOR_DEBUG_SPRAY_AIM_VECTOR_LENGTH_DEFAULT 36
#macro ACTOR_DEBUG_SPRAY_RECOIL_VECTOR_SCALE_DEFAULT 24
#macro ACTOR_DEBUG_SPRAY_ORIGIN_RADIUS_DEFAULT 3

#macro ACTOR_STEP_FPS 60
#macro ACTOR_EPSILON 0.0001
#macro ACTOR_MAX_COLLISION_ITERATIONS 16
#macro ACTOR_MAX_MOVE_STEP_PIXELS 2
#macro ACTOR_HARD_SPEED_CAP 24
#macro ACTOR_NO_HIT_DISTANCE 1000000
#macro ACTOR_SOLID_BASE_SIZE 32
#macro ACTOR_CONTACT_PROBE_DISTANCE 1
#macro ACTOR_COLLISION_SWEEP_REFINEMENT 0.125
#macro ACTOR_UNSTUCK_MAX_DISTANCE 8

#macro ACTOR_SLOPE_MAX_ANGLE_DEFAULT 45
#macro ACTOR_SLOPE_SNAP_DISTANCE_DEFAULT 8
#macro ACTOR_SLOPE_STEP_HEIGHT_DEFAULT 6
#macro ACTOR_ONE_WAY_DROP_NUDGE_DEFAULT 2
#macro ACTOR_MOVING_PLATFORM_DISTANCE_DEFAULT 96
#macro ACTOR_MOVING_PLATFORM_SPEED_DEFAULT 1
#macro ACTOR_PLATFORM_INHERIT_X_MULTIPLIER_DEFAULT 1
#macro ACTOR_PLATFORM_INHERIT_Y_UP_MULTIPLIER_DEFAULT 1
#macro ACTOR_PLATFORM_INHERIT_Y_DOWN_MULTIPLIER_DEFAULT 0

#macro ACTOR_JUMP_BUFFER_FRAMES_DEFAULT 8
#macro ACTOR_GROUND_COYOTE_FRAMES_DEFAULT 8
#macro ACTOR_WALL_COYOTE_FRAMES_DEFAULT 6
#macro ACTOR_LEDGE_COYOTE_FRAMES_DEFAULT 5
#macro ACTOR_DROP_THROUGH_FRAMES_DEFAULT 12
#macro ACTOR_WALL_JUMP_LOCKOUT_FRAMES_DEFAULT 6

#macro ACTOR_SPRAY_GROUND_LIFT_SUPPRESS true
#macro ACTOR_GROUND_LAUNCH_CHARGE_MIN_DEFAULT 0.65
#macro ACTOR_WATER_MAX_DEFAULT 100
#macro ACTOR_EMPTY_SPRAY_GRACE_FRAMES_DEFAULT 3
#macro ACTOR_SPRAY_WIDE_COST_DEFAULT 0.35
#macro ACTOR_SPRAY_WIDE_RECOIL_DEFAULT 0.60
#macro ACTOR_SPRAY_FOCUSED_COST_DEFAULT 0.75
#macro ACTOR_SPRAY_FOCUSED_RECOIL_DEFAULT 1.10
#macro ACTOR_SPRAY_RECOIL_DURATION_FRAMES_DEFAULT 1
#macro ACTOR_SPRAY_RECOIL_DAMPING_DEFAULT 1
#macro ACTOR_SPRAY_RECOIL_CONTROL_REDUCTION_DEFAULT 0
#macro ACTOR_WATER_REFILL_RATE_DEFAULT 1.5
#macro ACTOR_CHARGE_BUILD_FRAMES_DEFAULT 45
#macro ACTOR_CHARGED_SHOT_COST_DEFAULT 18
#macro ACTOR_CHARGED_SHOT_IMPULSE_DEFAULT 7.0
#macro ACTOR_CHARGED_SHOT_DURATION_FRAMES_DEFAULT 8
#macro ACTOR_CHARGED_SHOT_DAMPING_DEFAULT 0.82
#macro ACTOR_CHARGED_SHOT_CONTROL_REDUCTION_DEFAULT 0.15

#macro ACTOR_ABILITY_NONE 0
#macro ACTOR_ABILITY_JUMP (1 << 0)
#macro ACTOR_ABILITY_WALL_SLIDE (1 << 1)
#macro ACTOR_ABILITY_WALL_JUMP (1 << 2)
#macro ACTOR_ABILITY_LEDGE_GRAB (1 << 3)
#macro ACTOR_ABILITY_SLIDE (1 << 4)
#macro ACTOR_ABILITY_SPRAY (1 << 5)
#macro ACTOR_ABILITY_CHARGE_SPRAY (1 << 6)
#macro ACTOR_ABILITY_DROP_THROUGH (1 << 7)
#macro ACTOR_ABILITY_ALL (ACTOR_ABILITY_JUMP | ACTOR_ABILITY_WALL_SLIDE | ACTOR_ABILITY_WALL_JUMP | ACTOR_ABILITY_LEDGE_GRAB | ACTOR_ABILITY_SLIDE | ACTOR_ABILITY_SPRAY | ACTOR_ABILITY_CHARGE_SPRAY | ACTOR_ABILITY_DROP_THROUGH)
